exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('restaurants').del()
  await knex('restaurants').insert([
    {
      id: 1,
      restaurant_name: 'Sushi Haven',
      cuisine: 'Japanese',
      description: 'Fresh and flavorful sushi creations',
      about: 'Sushi Haven offers a diverse menu of sushi rolls, sashimi, and Japanese delights.',
      contact_phone: '456-789-0123',
      contact_email: 'info@sushihaven.com',
      image_url: 'https://example.com/sushihaven.jpg',
    },
    {
      id: 2,
      restaurant_name: 'Curry Palace',
      cuisine: 'Indian',
      description: 'Rich and aromatic Indian curries',
      about: 'Curry Palace brings the authentic flavors of India with a variety of curry dishes.',
      contact_phone: '789-012-3456',
      contact_email: 'info@currypalace.com',
      image_url: 'https://example.com/currypalace.jpg',
    },
    {
      id: 3,
      restaurant_name: 'Burger Bliss',
      cuisine: 'American',
      description: 'Classic American burgers done right',
      about: 'Burger Bliss is your destination for mouthwatering burgers and all-American favorites.',
      contact_phone: '234-567-8901',
      contact_email: 'info@burgerbliss.com',
      image_url: 'https://example.com/burgerbliss.jpg',
    },
    {
      id: 4,
      restaurant_name: 'Mediterranean Delight',
      cuisine: 'Mediterranean',
      description: 'Fresh and healthy Mediterranean cuisine',
      about: 'Mediterranean Delight offers a taste of the Mediterranean with fresh and nutritious dishes.',
      contact_phone: '567-890-1234',
      contact_email: 'info@mediterraneandelight.com',
      image_url: 'https://example.com/mediterraneandelight.jpg',
    },
    {
      id: 5,
      restaurant_name: 'Taco Fiesta',
      cuisine: 'Mexican',
      description: 'Tacos, burritos, and Mexican fiesta flavors',
      about: 'Taco Fiesta is the go-to spot for an authentic Mexican fiesta in every bite.',
      contact_phone: '890-123-4567',
      contact_email: 'info@tacofiesta.com',
      image_url: 'https://example.com/tacofiesta.jpg',
    },
    {
      id: 6,
      restaurant_name: 'Peking Wok',
      cuisine: 'Chinese',
      description: 'Savory and delicious Chinese cuisine',
      about: 'Peking Wok serves up a delectable selection of Chinese dishes with bold flavors.',
      contact_phone: '123-456-7890',
      contact_email: 'info@pekingwok.com',
      image_url: 'https://example.com/pekingwok.jpg',
    },
    {
      id: 7,
      restaurant_name: 'BBQ Barn',
      cuisine: 'Barbecue',
      description: 'Slow-cooked barbecue goodness',
      about: 'BBQ Barn brings the smoky and savory flavors of slow-cooked barbecue to your plate.',
      contact_phone: '987-654-3210',
      contact_email: 'info@bbqbarn.com',
      image_url: 'https://example.com/bbqbarn.jpg',
    },
    {
      id: 8,
      restaurant_name: 'Vegan Vibes',
      cuisine: 'Vegetarian/Vegan',
      description: 'Plant-based delights for a healthier you',
      about: 'Vegan Vibes offers a menu full of delicious and wholesome plant-based dishes.',
      contact_phone: '321-654-0987',
      contact_email: 'info@veganvibes.com',
      image_url: 'https://example.com/veganvibes.jpg',
    },
    {
      id: 9,
      restaurant_name: 'Seafood Harbor',
      cuisine: 'Seafood',
      description: 'Fresh catches and seafood delights',
      about: 'Seafood Harbor is your harbor for the freshest catches and delicious seafood meals.',
      contact_phone: '876-543-2109',
      contact_email: 'info@seafoodharbor.com',
      image_url: 'https://example.com/seafoodharbor.jpg',
    },
    {
      id: 10,
      restaurant_name: 'Pizza Palace',
      cuisine: 'Italian',
      description: 'Delicious pizzas with a variety of toppings',
      about: 'Pizza Palace serves up mouthwatering pizzas with a wide selection of tasty toppings.',
      contact_phone: '543-210-9876',
      contact_email: 'info@pizzapalace.com',
      image_url: 'https://example.com/pizzapalace.jpg',
    },
    {
      id: 11,
      restaurant_name: 'Healthy Bites',
      cuisine: 'Vegetarian/Vegan',
      description: 'Nutritious and flavorful dishes for a healthy lifestyle',
      about: 'Healthy Bites is your destination for nutritious and delicious meals to support your well-being.',
      contact_phone: '210-987-6543',
      contact_email: 'info@healthybites.com',
      image_url: 'https://example.com/healthybites.jpg',
    },
    {
      id: 12,
      restaurant_name: 'Pasta Paradise',
      cuisine: 'Italian',
      description: 'Authentic Italian flavors in every dish',
      about: 'Pasta Paradise is your go-to place for delicious and traditional Italian cuisine.',
      contact_phone: '123-456-7890',
      contact_email: 'info@pastaparadise.com',
      image_url: 'https://example.com/pastaparadise.jpg',
    },
    {
      id: 13,
      restaurant_name: 'Spicy Salsa',
      cuisine: 'Mexican',
      description: 'Bold and flavorful Mexican dishes',
      about: 'Spicy Salsa brings the heat with its mouthwatering selection of Mexican delicacies.',
      contact_phone: '987-654-3210',
      contact_email: 'info@spicysalsa.com',
      image_url: 'https://example.com/spicysalsa.jpg',
    },
    {
      id: 14,
      restaurant_name: 'Pao by Paul Qui',
      cuisine: 'Filipino',
      description: 'Bold and flavorful Filipino dishes',
      about: 'Pao boldly reflects celebrated chef Paul Qui\'s renowned brand of modern Asian cuisine drawing from his background and range of international styles, including Filipino, Spanish, Japanese, and French.',
      contact_phone: '987-654-3210',
      contact_email: 'info@paobypaulque.com',
      image_url: 'https://example.com/paobypaulque.jpg',
    }
  ]);
};
